swagger: "2.0"
produces:
- application/json
schemes:
- http
consumes:
- application/json
info:
  contact:
    email: curtis.myzie@gmail.com
    name: Curtis Myzie
  description: Blob Storage
  title: Blobs
  version: 0.0.1
paths:
  /blobs:
    get:
      summary: List blobs
      operationId: listBlobs
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time
          type: integer
        - name: offset
          in: query
          description: Offset into search results
          type: integer
      responses:
        "200":
          description: Array of blobs
          schema:
            $ref: '#/definitions/Blobs'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/BlobsError'
definitions:
  Blob:
    description: "Binary Object"
    type: object
    properties:
      id:
        type: string
        description: "Unique identifier"
      name:
        type: string
        description: "User provided name"
      created_at:
        type: string
        format: dateTime
        description: "Time when sound was added"
      updated_at:
        type: string
        format: dateTime
        description: "Time when sound was updated"
      path:
        type: string
        description: "Storage path"
        maxLength: 200
  Blobs:
    type: array
    items:
      $ref: '#/definitions/Blob'
  BlobAttributes:
    description: "Blob attributes set by the user"
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      path:
        type: string
        description: "Storage path"
        maxLength: 200
      properties:
        type: object
        additionalProperties: true
  BlobsError:
    description: Error that occurred while processing the request
    type: object
    required:
      - message
      - code
    properties:
      code:
        description: The error code
        type: integer
      message:
        description: The error message
        type: string
